menu:
  Home: /
  Archives: /archives
  Categories: /categories
  Tags: /tags
  About: /about

subtitle:
  enable: true
  text: Software Development.
  text2: Tech Stuff.
  text3: Bunnies.
  startDelay: 0
  typeSpeed: 200
  loop: true
  backSpeed: 100
  showCursor: true

# Favicon and sidebar logo
favicon: /favicon.ico
logo: /images/goober.png

# Cover Setting
# enable: [true|false]；path: [background-image]；logo: [cover-logo-image]
cover:
  enable: true
  path: /images/plett1.jpg # there are some beautiful cover images in Ayer's directory: /source/images, choose your favorite image to replace it.

# ProgressBar
progressBar: true

github:
  enable: false

ads:

nav_text:
  page_prev: Previous Page 
  page_next: Next Page
  post_prev: Previous Post
  post_next: Next Post
 