menu:
  Home: /
  Archives: /archives
  Categories: /categories
  Tags: /tags
  About: /about

subtitle:
  enable: true
  text: Software Development.
  text2: Tech Stuff.
  text3: Bunnies.
  startDelay: 0
  typeSpeed: 200
  loop: true
  backSpeed: 100
  showCursor: true

# Favicon and sidebar logo
favicon: /favicon.ico
logo: /images/goober.png

# Cover Setting
# enable: [true|false]；path: [background-image]；logo: [cover-logo-image]
cover:
  enable: true
  path: /images/plett1.jpg # there are some beautiful cover images in Ayer's directory: /source/images, choose your favorite image to replace it.

# ProgressBar
progressBar: true

github:
  enable: false

ads:

nav_text:
  page_prev: Previous Page 
  page_next: Next Page
  post_prev: Previous Post
  post_next: Next Post
 
share_enable: false

excerpt_link: Read more
excerpt_all: false

google_analytics: "G-KXJW9BVBJ4"

search:
    path: search.xml
    field: post
    format: html

gitalk:
  enable: true
  clientID: 8318211c28156a054b60
  clientSecret: a3e7c2c22e61867951cbca3c52fbcc22f43dcfb8
  repo: BlogComments
  owner: nickmza
  admin: nickmza